/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as crosschain from "./crosschain";
export type { crosschain };
import type * as diamond from "./diamond";
export type { diamond };
import type * as migration from "./migration";
export type { migration };
import type * as mock from "./mock";
export type { mock };
import type * as registrar from "./registrar";
export type { registrar };
import type * as registry from "./registry";
export type { registry };
import type * as rental from "./rental";
export type { rental };
import type * as resolver from "./resolver";
export type { resolver };
import type * as root from "./root";
export type { root };
import type * as utils from "./utils";
export type { utils };
import type * as wrapper from "./wrapper";
export type { wrapper };
