/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { Helper, HelperInterface } from "../../../contracts/utils/Helper";

const _abi = [
  {
    inputs: [],
    name: "MAX_LABEL_LENGTH",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MIN_LABEL_LENGTH",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "label",
        type: "bytes",
      },
    ],
    name: "valid",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

export class Helper__factory {
  static readonly abi = _abi;
  static createInterface(): HelperInterface {
    return new Interface(_abi) as HelperInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Helper {
    return new Contract(address, _abi, runner) as unknown as Helper;
  }
}
