/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface ITypedTextResolverInterface extends ethers.utils.Interface {
  functions: {
    "getTypedText(bytes,bytes,bytes,bytes)": FunctionFragment;
    "setTypedText(bytes,bytes,bytes,bytes,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getTypedText",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTypedText",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getTypedText",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTypedText",
    data: BytesLike
  ): Result;

  events: {
    "SetTypedText(bytes,bytes,bytes,bytes,string)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SetTypedText"): EventFragment;
}

export type SetTypedTextEvent = TypedEvent<
  [string, string, string, string, string] & {
    host: string;
    name: string;
    tld: string;
    type_: string;
    text: string;
  }
>;

export class ITypedTextResolver extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ITypedTextResolverInterface;

  functions: {
    getTypedText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      type_: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    setTypedText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      type_: BytesLike,
      text: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getTypedText(
    host: BytesLike,
    name: BytesLike,
    tld: BytesLike,
    type_: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  setTypedText(
    host: BytesLike,
    name: BytesLike,
    tld: BytesLike,
    type_: BytesLike,
    text: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getTypedText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      type_: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    setTypedText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      type_: BytesLike,
      text: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "SetTypedText(bytes,bytes,bytes,bytes,string)"(
      host?: null,
      name?: null,
      tld?: null,
      type_?: null,
      text?: null
    ): TypedEventFilter<
      [string, string, string, string, string],
      { host: string; name: string; tld: string; type_: string; text: string }
    >;

    SetTypedText(
      host?: null,
      name?: null,
      tld?: null,
      type_?: null,
      text?: null
    ): TypedEventFilter<
      [string, string, string, string, string],
      { host: string; name: string; tld: string; type_: string; text: string }
    >;
  };

  estimateGas: {
    getTypedText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      type_: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setTypedText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      type_: BytesLike,
      text: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getTypedText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      type_: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setTypedText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      type_: BytesLike,
      text: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
